version: "3.7"

services:
  db:
    image: postgres:15.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: dscatalog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dscatalog-network

  pgadmin:
    image: dpage/pgadmin4:7.0
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    networks:
      - dscatalog-network

volumes:
  db-data:
  pgadmin-data:


networks:
  dscatalog-network:
    driver: bridge
