spring:
  datasource:
    password: 1234567
    url: jdbc:postgresql://localhost:5432/dscatalog
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
