jwt:
  duration: ${JWT_DURATION:86400}
  secret: ${JWT_SECRET:MY-JWT-SECRET}
security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:dscatalog}
      client-secret: ${CLIENT_SECRET:dscatalog123}
spring:
  jpa:
    open-in-view: false
  profiles:
    active: ${APP_PROFILE:test}
